// ── Study notes for the exercise page ────────────────────────────────────────
// What studies found about an exercise, shown word for word from the verified
// evidence register. GENERATED by scripts/evidence/build.mjs from
// docs/research/workout-mode/evidence.json — do not hand-edit. 49 notes.
// Lazy-load it with the exercise page; the logger and the maths never import it.

import type { Exercise } from "./exerciseData";

export type Grade = "A" | "B" | "C";

export interface StudyNote {
  id: string;
  grade: Grade;
  text: string; // correctedClaim, word for word
  attach: "this" | "variation" | "category"; // variation = tested on a similar exercise, not this one
  sources: { citation: string; url: string }[];
}

type Attach = StudyNote["attach"];

export const STUDY_NOTES: readonly Omit<StudyNote, "attach">[] = [
  {
    id: "squat-depth-glutes",
    grade: "A",
    text: "Full-depth squats grew the glutes and inner-thigh adductors about two to three times more than half squats, while front-thigh growth was about the same.",
    sources: [
      { citation: "Kubo K, Ikebukuro T, Yata H. Effects of squat training with different depths on lower limb muscle volumes. Eur J Appl Physiol. 2019;119(9):1933-1942. doi:10.1007/s00421-019-04181-y", url: "https://europepmc.org/article/MED/31230110" },
    ],
  },
  {
    id: "squat-depth-quads",
    grade: "A",
    text: "In 17 young men over 12 weeks, deep squats (knee bent to about 120°) grew the front of the thigh at every measured spot (4–7%), while shallow squats (about 60°) grew it only near the hip, so deep squats came out ahead.",
    sources: [
      { citation: "Bloomquist K, Langberg H, Karlsen S, et al. Effect of range of motion in heavy load squatting on muscle and tendon adaptations. Eur J Appl Physiol. 2013;113(8):2133-2142. doi:10.1007/s00421-013-2642-7", url: "https://europepmc.org/article/MED/23604798" },
      { citation: "Kubo K, Ikebukuro T, Yata H. Eur J Appl Physiol. 2019;119(9):1933-1942. doi:10.1007/s00421-019-04181-y", url: "https://europepmc.org/article/MED/31230110" },
    ],
  },
  {
    id: "squat-no-hamstrings",
    grade: "A",
    text: "Myth check: in small 9–12 week MRI studies of young, mostly untrained adults, squats grew the hamstrings little or not at all. One found no change in whole-muscle volume, one found none at a single upper-thigh slice, and a third found a gain at only one of six spots.",
    sources: [
      { citation: "Kubo K, Ikebukuro T, Yata H. Eur J Appl Physiol. 2019;119(9):1933-1942. doi:10.1007/s00421-019-04181-y", url: "https://europepmc.org/article/MED/31230110" },
      { citation: "Plotkin DL, Rodas MA, Vigotsky AD, et al. Hip thrust and back squat training elicit similar gluteus muscle hypertrophy and transfer similarly to the deadlift. Front Physiol. 2023;14:1279170. doi:10.3389/fphys.2023.1279170", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC10593473/" },
      { citation: "Bloomquist K, Langberg H, Karlsen S, et al. Eur J Appl Physiol. 2013;113(8):2133-2142. doi:10.1007/s00421-013-2642-7", url: "https://europepmc.org/article/MED/23604798" },
    ],
  },
  {
    id: "squat-rectus-femoris",
    grade: "A",
    text: "In one 10-week MRI study, squats grew the quadriceps overall but not the rectus femoris, the one quad muscle that also crosses the hip; the leg press showed the same pattern in a separate study.",
    sources: [
      { citation: "Kubo K, Ikebukuro T, Yata H. Eur J Appl Physiol. 2019;119(9):1933-1942. doi:10.1007/s00421-019-04181-y", url: "https://europepmc.org/article/MED/31230110" },
      { citation: "Kinoshita M, Maeo S, Kobayashi Y, et al. Hypertrophic Effects of Single- versus Multi-Joint Exercise: A Direct Comparison between Knee Extension and Leg Press. Med Sci Sports Exerc. 2026;58(7):1566-1580. doi:10.1249/mss.0000000000003957", url: "https://europepmc.org/article/MED/41630124" },
    ],
  },
  {
    id: "hipthrust-vs-squat-glutes",
    grade: "A",
    text: "Over 9 weeks, hip thrusts and back squats grew the glutes about equally in beginners, but squats also grew the quads and adductors more.",
    sources: [
      { citation: "Plotkin DL, Rodas MA, Vigotsky AD, et al. Front Physiol. 2023;14:1279170. doi:10.3389/fphys.2023.1279170", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC10593473/" },
    ],
  },
  {
    id: "hipthrust-emg-not-growth",
    grade: "A",
    text: "Myth check: hip thrusts switched on the glutes more than squats, but in the same study of beginners that extra activation did not reliably turn into extra glute growth.",
    sources: [
      { citation: "Plotkin DL, Rodas MA, Vigotsky AD, et al. Front Physiol. 2023;14:1279170. doi:10.3389/fphys.2023.1279170", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC10593473/" },
      { citation: "Vigotsky AD, Halperin I, Lehman GJ, Trajano GS, Vieira TM. Interpreting Signal Amplitudes in Surface Electromyography Studies in Sport and Rehabilitation Sciences. Front Physiol. 2017;8:985. doi:10.3389/fphys.2017.00985", url: "https://europepmc.org/article/MED/29354060" },
    ],
  },
  {
    id: "hipthrust-emg-numbers",
    grade: "B",
    text: "With estimated 10-rep-max weights, the barbell hip thrust produced roughly twice the average glute activity of the back squat, with similar front-thigh activity, in 13 trained women.",
    sources: [
      { citation: "Contreras B, Vigotsky AD, Schoenfeld BJ, Beardsley C, Cronin J. A Comparison of Gluteus Maximus, Biceps Femoris, and Vastus Lateralis Electromyographic Activity in the Back Squat and Barbell Hip Thrust Exercises. J Appl Biomech. 2015;31(6):452-458. doi:10.1123/jab.2014-0301", url: "https://europepmc.org/article/MED/26214739" },
    ],
  },
  {
    id: "glute-medius-little-growth",
    grade: "A",
    text: "Neither hip thrusts nor squats grew the side glutes (glute medius and minimus) much in beginners over 9 weeks.",
    sources: [
      { citation: "Plotkin DL, Rodas MA, Vigotsky AD, et al. Front Physiol. 2023;14:1279170. doi:10.3389/fphys.2023.1279170", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC10593473/" },
    ],
  },
  {
    id: "glute-bridge-anatomy",
    grade: "C",
    text: "The glute bridge uses the same hip-straightening action as the hip thrust over a shorter range, so the glutes are expected to do most of the work with the hamstrings helping.",
    sources: [],
  },
  {
    id: "leg-press-glutes",
    grade: "A",
    text: "In 17 untrained adults training one leg on each machine for 12 weeks, the leg press grew the gluteus maximus about 15% and the adductor magnus about 6%, but not the glute medius or minimus, and it grew the three vasti (front-thigh muscles) as much as leg extensions did.",
    sources: [
      { citation: "Kinoshita M, Maeo S, Kobayashi Y, et al. Med Sci Sports Exerc. 2026;58(7):1566-1580. doi:10.1249/mss.0000000000003957", url: "https://europepmc.org/article/MED/41630124" },
    ],
  },
  {
    id: "leg-extension-rectus-femoris",
    grade: "A",
    text: "In a 12-week MRI study of untrained adults, leg extensions grew the rectus femoris about 13% while leg presses grew it about 1% (not a real change); a smaller ultrasound study whose measurement method was disputed points the same way.",
    sources: [
      { citation: "Kinoshita M, Maeo S, Kobayashi Y, et al. Med Sci Sports Exerc. 2026;58(7):1566-1580. doi:10.1249/mss.0000000000003957", url: "https://europepmc.org/article/MED/41630124" },
      { citation: "Zabaleta-Korta A, Fernández-Peña E, Torres-Unda J, Garbisu-Hualde A, Santos-Concejero J. The role of exercise selection in regional muscle hypertrophy: A randomized controlled trial. J Sports Sci. 2021;39(20):2298-2304. doi:10.1080/02640414.2021.1929736", url: "https://europepmc.org/article/MED/34743671" },
      { citation: "Leitão BFM, Franchi MV, da Matta TT. Letter to the editor concerning the article by Zabaleta-Korta et al. (2021). J Sports Sci. 2022;40(6):655-657. doi:10.1080/02640414.2021.2013596", url: "https://europepmc.org/article/MED/34930094" },
    ],
  },
  {
    id: "leg-extension-stretched-half",
    grade: "A",
    text: "Leg extensions done only in the bottom half, where the knee is bent and the quads are stretched, grew parts of the thigh more than full-range or top-half reps in untrained women.",
    sources: [
      { citation: "Pedrosa GF, Lima FV, Schoenfeld BJ, et al. Partial range of motion training elicits favorable improvements in muscular adaptations when carried out at long muscle lengths. Eur J Sport Sci. 2022;22(8):1250-1260. doi:10.1080/17461391.2021.1927199", url: "https://europepmc.org/article/MED/33977835" },
      { citation: "Varovic D, Wolf M, Schoenfeld BJ, Steele J, Grgic J, Mikulic P. Does Muscle Length Influence Regional Hypertrophy? A Systematic Review and Meta-Analysis. Int J Sports Med. 2025;46(14):1027-1036. doi:10.1055/a-2615-4935", url: "https://europepmc.org/article/MED/40570881" },
    ],
  },
  {
    id: "seated-vs-lying-leg-curl",
    grade: "A",
    text: "Seated leg curls grew the hamstrings more than lying leg curls (about 14% vs 9%), likely because the bent hip keeps the hamstrings stretched.",
    sources: [
      { citation: "Maeo S, Huang M, Wu Y, et al. Greater Hamstrings Muscle Hypertrophy but Similar Damage Protection after Training at Long versus Short Muscle Lengths. Med Sci Sports Exerc. 2021;53(4):825-837. doi:10.1249/MSS.0000000000002523", url: "https://europepmc.org/article/MED/33009197" },
    ],
  },
  {
    id: "hip-extension-bflh",
    grade: "A",
    text: "A straight-knee 45° hip-extension exercise grew the outer hamstring (biceps femoris long head) more than Nordic curls, while both grew the inner semitendinosus.",
    sources: [
      { citation: "Bourne MN, Duhig SJ, Timmins RG, et al. Impact of the Nordic hamstring and hip extension exercises on hamstring architecture and morphology: implications for injury prevention. Br J Sports Med. 2017;51(5):469-477. doi:10.1136/bjsports-2016-096130", url: "https://europepmc.org/article/MED/27660368" },
    ],
  },
  {
    id: "nordic-curl",
    grade: "A",
    text: "Nordic curls grew the semitendinosus and lengthened the fascicles (fibre bundles) of the outer hamstring. Hip extensions and Romanian deadlifts lengthened them just as much, and the lengthening faded within two weeks of stopping.",
    sources: [
      { citation: "Bourne MN, Duhig SJ, Timmins RG, et al. Br J Sports Med. 2017;51(5):469-477. doi:10.1136/bjsports-2016-096130", url: "https://europepmc.org/article/MED/27660368" },
      { citation: "Arin-Bal G, Comlekci M, Pakoz B, Uysal O, Bayrakci-Tunay V. Effect of Hamstring Exercises on Morphological Parameters of the Hamstring Muscle: A Systematic Review With MRI and USI Findings. Sports Health. 2026. doi:10.1177/19417381261463404", url: "https://europepmc.org/article/MED/42460513" },
      { citation: "Crawford et al. Med Sci Sports Exerc. 2025. doi:10.1249/mss.0000000000003701", url: "https://europepmc.org/article/MED/40085810" },
    ],
  },
  {
    id: "rdl-anatomy",
    grade: "C",
    text: "The Romanian deadlift bends at the hips with nearly straight knees, so it loads the hamstrings and glutes while they are stretched.",
    sources: [
      { citation: "Bourne MN, Duhig SJ, Timmins RG, et al. Br J Sports Med. 2017;51(5):469-477 (related exercise, not the RDL). doi:10.1136/bjsports-2016-096130", url: "https://europepmc.org/article/MED/27660368" },
    ],
  },
  {
    id: "deadlift-anatomy",
    grade: "C",
    text: "The conventional deadlift straightens the hips and knees at the same time, so the hip extensors (glutes, adductors, hamstrings) and back muscles carry the load, the quads help mostly as the bar leaves the floor, and the hamstrings change length less than in a Romanian deadlift.",
    sources: [],
  },
  {
    id: "standing-vs-seated-calf",
    grade: "A",
    text: "Standing calf raises grew the gastrocnemius by about 9–12%, while seated calf raises barely grew it (under 2%).",
    sources: [
      { citation: "Kinoshita M, Maeo S, Kobayashi Y, et al. Triceps surae muscle hypertrophy is greater after standing versus seated calf-raise training. Front Physiol. 2023;14:1272106. doi:10.3389/fphys.2023.1272106", url: "https://europepmc.org/article/MED/38156065" },
    ],
  },
  {
    id: "seated-calf-soleus-myth",
    grade: "A",
    text: "Myth check: in one 12-week MRI study of 14 untrained adults, seated calf raises did not grow the soleus any more than standing calf raises did (2.9% vs 2.1%, not a significant difference), so 'seated for the soleus' is unproven.",
    sources: [
      { citation: "Kinoshita M, Maeo S, Kobayashi Y, et al. Front Physiol. 2023;14:1272106. doi:10.3389/fphys.2023.1272106", url: "https://europepmc.org/article/MED/38156065" },
    ],
  },
  {
    id: "calf-stretched-half",
    grade: "A",
    text: "In one 8-week ultrasound study of 42 young women doing calf raises on a leg-press machine, bottom-half (stretched) reps grew the inner calf head more than full-range or top-half reps, but for the outer calf head they only beat top-half reps, not full-range reps.",
    sources: [
      { citation: "Kassiano W, Costa B, Kunevaliki G, et al. Greater Gastrocnemius Muscle Hypertrophy After Partial Range of Motion Training Performed at Long Muscle Lengths. J Strength Cond Res. 2023;37(9):1746-1753. doi:10.1519/jsc.0000000000004460", url: "https://europepmc.org/article/MED/37015016" },
      { citation: "Larsen S, Sandberg NØ, Schoenfeld BJ, et al. Resistance Training Beyond Momentary Failure: The Effects of Past-Failure Partials Versus Initial Partials on Calf Muscle Hypertrophy Among a Resistance-Trained Cohort. Eur J Sport Sci. 2025;25(9):e70030. doi:10.1002/ejsc.70030", url: "https://europepmc.org/article/MED/40850937" },
    ],
  },
  {
    id: "calf-toe-direction",
    grade: "A",
    text: "In one 9-week ultrasound study of 22 young men doing calf raises on a leg-press machine, pointing the toes out grew the inner calf head more than pointing them in, and pointing them in grew the outer calf head more than pointing them out; toes-forward was not clearly different from either.",
    sources: [
      { citation: "Nunes JP, Costa BDV, Kassiano W, et al. Different Foot Positioning During Calf Training to Induce Portion-Specific Gastrocnemius Muscle Hypertrophy. J Strength Cond Res. 2020;34(8):2347-2351. doi:10.1519/jsc.0000000000003674", url: "https://europepmc.org/article/MED/32735428" },
    ],
  },
  {
    id: "incline-bench-upper-chest",
    grade: "A",
    text: "In one 8-week ultrasound study of untrained young men training once a week, a 44° incline bench press grew the upper chest more than the flat bench press; at the middle and lower chest the incline group's gains were numerically larger but not significantly different.",
    sources: [
      { citation: "Chaves SFN, Rocha-Júnior VA, Encarnação IGA, et al. Effects of Horizontal and Incline Bench Press on Neuromuscular Adaptations in Untrained Young Men. Int J Exerc Sci. 2020;13(6):859-872.", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC7449336/" },
    ],
  },
  {
    id: "incline-angle-emg",
    grade: "B",
    text: "In one EMG study of 30 trained adults at 60% of max, upper-chest activity was numerically highest at a 30° incline but not significantly different from flat, 15° or 45°; it dropped at 60°, and front-shoulder activity was significantly higher at 45° and 60°.",
    sources: [
      { citation: "Rodríguez-Ridao D, Antequera-Vique JA, Martín-Fuentes I, Muyor JM. Effect of Five Bench Inclinations on the Electromyographic Activity of the Pectoralis Major, Anterior Deltoid, and Triceps Brachii during the Bench Press Exercise. Int J Environ Res Public Health. 2020;17(19):7339. doi:10.3390/ijerph17197339", url: "https://europepmc.org/article/MED/33049982" },
    ],
  },
  {
    id: "flat-bench-emg",
    grade: "B",
    text: "Of five bench angles tested in one EMG study of 30 trained adults at 60% of max, the flat bench gave the highest middle- and lower-chest activity.",
    sources: [
      { citation: "Rodríguez-Ridao D, Antequera-Vique JA, Martín-Fuentes I, Muyor JM. Int J Environ Res Public Health. 2020;17(19):7339. doi:10.3390/ijerph17197339", url: "https://europepmc.org/article/MED/33049982" },
    ],
  },
  {
    id: "machine-chest-press-emg",
    grade: "B",
    text: "In one EMG study of 20 experienced lifters doing 8 reps at 60% of max, a seated chest-press machine and the bench press produced broadly similar chest, front-shoulder and triceps activity, with slightly higher upper-chest activity on the machine with a neutral grip.",
    sources: [
      { citation: "Muyor JM, Rodríguez-Ridao D, Oliva-Lozano JM. Comparison of Muscle Activity between the Horizontal Bench Press and the Seated Chest Press Exercises Using Several Grips. J Hum Kinet. 2023;87:23-34. doi:10.5114/jhk/161468", url: "https://europepmc.org/article/MED/37229415" },
    ],
  },
  {
    id: "pushup-vs-bench-growth",
    grade: "A",
    text: "In one 8-week study of 18 recreationally trained young men, push-ups adjusted to match a 40%-of-max bench press, with every set taken to failure, grew the chest and triceps about as much as that bench press did.",
    sources: [
      { citation: "Kikuchi N, Nakazato K. Low-load bench press and push-up induce similar muscle hypertrophy and strength gain. J Exerc Sci Fit. 2017;15(1):37-42. doi:10.1016/j.jesf.2017.06.003", url: "https://europepmc.org/article/MED/29541130" },
    ],
  },
  {
    id: "band-pushup-strength",
    grade: "A",
    text: "In one 5-week randomized study of 30 experienced university lifters, band-resisted push-ups set to a 6-rep max produced strength gains similar to a 6-rep-max bench press; muscle size was not measured.",
    sources: [
      { citation: "Calatayud J, Borreani S, Colado JC, et al. Bench press and push-up at comparable levels of muscle activity results in similar strength gains. J Strength Cond Res. 2015;29(1):246-253. doi:10.1519/jsc.0000000000000589", url: "https://europepmc.org/article/MED/24983847" },
    ],
  },
  {
    id: "bodyweight-squat-older-adults",
    grade: "A",
    text: "In one 12-week study of 16 active adults around 70, home chair squats (4 sets of 35 reps, 3 days a week) improved sit-to-stand and leg-press strength, but thigh muscle thickness did not change measurably; the study was too small to rule out a modest gain.",
    sources: [
      { citation: "Yoshiko A, Watanabe K. Impact of home-based squat training with two-depths on lower limb muscle parameters and physical functional tests in older adults. Sci Rep. 2021;11(1):6855. doi:10.1038/s41598-021-86030-7", url: "https://europepmc.org/article/MED/33767255" },
    ],
  },
  {
    id: "bands-vs-weights-strength",
    grade: "A",
    text: "A meta-analysis of 8 trials (later corrected by the authors) found that training with elastic bands or tubes produced strength gains similar to training with weight machines and dumbbells; it did not measure muscle size.",
    sources: [
      { citation: "Lopes JSS, Machado AF, Micheletti JK, et al. Effects of training with elastic resistance versus conventional resistance on muscular strength: A systematic review and meta-analysis. SAGE Open Med. 2019;7:2050312119831116 (corrigendum 2020). doi:10.1177/2050312119831116", url: "https://europepmc.org/article/MED/30815258" },
    ],
  },
  {
    id: "band-colour-not-weight",
    grade: "B",
    text: "Band colours are not a reliable stand-in for dumbbell weights: in one study of 30 active adults, colour-coded elastic tubes matched the muscle activity of 2-6 kg dumbbells in only 2 of 4 upper-body exercises, and only for men.",
    sources: [
      { citation: "Martín-Ruiz J, Ruiz-Sanchis L, Tamarit Grancha I, et al. Comparison of Upper-Limb Muscle Activation Levels in Different Physical Fitness Exercises Using Dumbbells and Elastic Tubes. Sports Health. 2026;18(4):796-803. doi:10.1177/19417381251353769", url: "https://europepmc.org/article/MED/40734261" },
    ],
  },
  {
    id: "band-row-anatomy",
    grade: "C",
    text: "A band row trains the lats, mid-back and rear shoulders with the biceps helping, and because a band's tension rises as it stretches, the band pulls hardest near the end of the pull where it is most stretched.",
    sources: [
      { citation: "Uchida MC, et al. Thera-band elastic band tension: reference values for physical activity. J Phys Ther Sci. 2016.", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC4868225/" },
    ],
  },
  {
    id: "plank-long-lever",
    grade: "B",
    text: "In one EMG study of 19 people doing 30-second holds, moving the elbows further forward and tucking the pelvis under raised abdominal activity compared with a standard plank, with the elbows-forward change contributing more.",
    sources: [
      { citation: "Schoenfeld BJ, Contreras B, Tiryaki-Sonmez G, Willardson JM, Fontana F. An electromyographic comparison of a modified version of the plank with a long lever and posterior tilt versus the traditional plank exercise. Sports Biomech. 2014;13(3):296-306. doi:10.1080/14763141.2014.942355", url: "https://europepmc.org/article/MED/25325773" },
    ],
  },
  {
    id: "plank-anatomy",
    grade: "C",
    text: "The plank trains the abs and obliques by holding the lower back from sagging, rather than by bending the spine like a crunch.",
    sources: [],
  },
  {
    id: "ab-spot-reduction-myth",
    grade: "A",
    text: "Myth check: in one 6-week randomized trial of 24 sedentary adults eating a steady-calorie diet, ab exercises five days a week did not reduce belly fat, skinfolds or waist size compared with doing nothing, though ab endurance improved.",
    sources: [
      { citation: "Vispute SS, Smith JD, LeCheminant JD, Hurley KS. The effect of abdominal exercise on abdominal fat. J Strength Cond Res. 2011;25(9):2559-2564. doi:10.1519/jsc.0b013e3181fb4a46", url: "https://europepmc.org/article/MED/21804427" },
    ],
  },
  {
    id: "pulldown-grip-width-myth",
    grade: "B",
    text: "Myth check: in EMG studies, wide-grip pulldowns did not switch on the lats more than medium or narrow grips over the whole rep (one study found slightly more lat activity with a wide grip only on the way back up); no study we found has tested whether grip width changes how the back grows.",
    sources: [
      { citation: "Andersen V, Fimland MS, Wiik E, Skoglund A, Saeterbakken AH. Effects of grip width on muscle strength and activation in the lat pull-down. J Strength Cond Res. 2014;28(4):1135-1142. doi:10.1097/jsc.0000000000000232", url: "https://europepmc.org/article/MED/24662157" },
      { citation: "Buonsenso A, Di Fonza D, Di Claudio G, et al. Electromyographic Analysis of Back Muscle Activation During Lat Pulldown Exercise: Effects of Grip Variations and Forearm Orientation. J Funct Morphol Kinesiol. 2025;10(3):345. doi:10.3390/jfmk10030345", url: "https://europepmc.org/article/MED/40981044" },
      { citation: "Lusk SJ, Hale BD, Russell DM. Grip width and forearm orientation effects on muscle activity during the lat pull-down. J Strength Cond Res. 2010;24(7):1895-1900. doi:10.1519/jsc.0b013e3181ddb0ab", url: "https://europepmc.org/article/MED/20543740" },
    ],
  },
  {
    id: "pulldown-front",
    grade: "B",
    text: "In two small EMG studies of trained men, pulling the bar down in front of the head gave more lat activity than behind the neck while pulling down, though one found behind-the-neck higher on the way back up; a 2026 review calls the front pulldown only tentatively the best-supported setup.",
    sources: [
      { citation: "Di Fonza D, Di Claudio G, Colantuono G, et al. Electromyographic Analysis of Latissimus Dorsi Activation During Common Resistance Training Exercises: A Narrative Review. J Funct Morphol Kinesiol. 2026;11(3):315. doi:10.3390/jfmk11030315", url: "https://europepmc.org/article/MED/42647355" },
    ],
  },
  {
    id: "pulling-grows-biceps",
    grade: "A",
    text: "Pulling exercises grow the biceps too, but studies disagree on whether curls add more: pulldowns matched curls in one study, while curls grew the arm about twice as much as rows in another.",
    sources: [
      { citation: "Gentil P, Soares S, Bottaro M. Single vs. Multi-Joint Resistance Exercises: Effects on Muscle Strength and Hypertrophy. Asian J Sports Med. 2015;6(2):e24057. doi:10.5812/asjsm.24057", url: "https://europepmc.org/article/MED/26446291" },
      { citation: "Mannarino P, Matta T, Lima J, Simão R, Freitas de Salles B. Single-Joint Exercise Results in Higher Hypertrophy of Elbow Flexors Than Multijoint Exercise. J Strength Cond Res. 2021;35(10):2677-2681. doi:10.1519/jsc.0000000000003234", url: "https://europepmc.org/article/MED/31268995" },
    ],
  },
  {
    id: "seated-row-elbows",
    grade: "B",
    text: "In seated rows, a narrower grip and keeping the elbows closer to the body were each linked to higher lat activity, though they were tested separately.",
    sources: [
      { citation: "Di Fonza D, Di Claudio G, Colantuono G, et al. J Funct Morphol Kinesiol. 2026;11(3):315. doi:10.3390/jfmk11030315", url: "https://europepmc.org/article/MED/42647355" },
    ],
  },
  {
    id: "pullup-grip",
    grade: "B",
    text: "In small EMG studies, changing pull-up grip made little difference to lat activity (an underhand grip mainly added biceps activity), so grip can reasonably be chosen for comfort, though that last part is advice, not a tested finding.",
    sources: [
      { citation: "Di Fonza D, Di Claudio G, Colantuono G, et al. J Funct Morphol Kinesiol. 2026;11(3):315. doi:10.3390/jfmk11030315", url: "https://europepmc.org/article/MED/42647355" },
    ],
  },
  {
    id: "overhead-press-anatomy",
    grade: "C",
    text: "The overhead press works the front delts, side delts and triceps, with the upper chest helping more when pressing in front and the side and rear delts more when pressing behind the neck; the upper traps help rotate the shoulder blades.",
    sources: [
      { citation: "Coratella G, et al. Front Physiol. 2022. doi:10.3389/fphys.2022.825880", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC9354811/" },
    ],
  },
  {
    id: "lateral-raise-cable-vs-dumbbell",
    grade: "A",
    text: "Myth check: cable and dumbbell lateral raises grew the side delts by similar amounts in trained lifters, even though cables keep more tension at the bottom.",
    sources: [
      { citation: "Larsen S, Wolf M, Schoenfeld BJ, et al. Dumbbell versus cable lateral raises for lateral deltoid hypertrophy: an experimental study. Front Physiol. 2025;16:1611468. doi:10.3389/fphys.2025.1611468", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12277279/" },
    ],
  },
  {
    id: "curl-stretched-range",
    grade: "A",
    text: "Preacher curls done only in the straight-arm part of the movement (0–50°) grew the upper-arm flexors about 2.6 times more than curls done only in the bent-arm part (80–130°), in untrained adults over 5 weeks.",
    sources: [
      { citation: "Sato S, Yoshida R, Kiyono R, et al. Elbow Joint Angles in Elbow Flexor Unilateral Resistance Exercise Training Determine Its Effects on Muscle Strength and Thickness of Trained and Non-trained Arms. Front Physiol. 2021;12:734509. doi:10.3389/fphys.2021.734509", url: "https://europepmc.org/article/MED/34616309" },
      { citation: "Zabaleta-Korta A, Fernández-Peña E, Torres-Unda J, et al. Regional Hypertrophy: The Effect of Exercises at Long and Short Muscle Lengths in Recreationally Trained Women. J Hum Kinet. 2023;87:259-270. doi:10.5114/jhk/163561", url: "https://europepmc.org/article/MED/37559762" },
    ],
  },
  {
    id: "preacher-curl-partials-trained",
    grade: "A",
    text: "In trained lifters, preacher curls done only in the bottom, stretched half grew the arm about as much as full-range preacher curls, with at most a small edge near the elbow.",
    sources: [
      { citation: "Havers T, Wagner N, Held S, Geisler S, Wiewelhove T. Partial Range, Full Gains? The Effect of 8 Weeks of Partial Range of Motion Training at Long Muscle Lengths on Elbow Flexor Hypertrophy and Strength in Trained Individuals. Eur J Sport Sci. 2025;25(12):e70087. doi:10.1002/ejsc.70087", url: "https://europepmc.org/article/MED/41247250" },
    ],
  },
  {
    id: "behind-body-curl-myth",
    grade: "A",
    text: "Myth check: curling with the arm pulled back behind the body did not grow the biceps more than a normal cable curl when range and resistance were matched.",
    sources: [
      { citation: "Larsen S, Sandvik Kristiansen B, Østerås Sandberg N, et al. The effects of shoulder extension angle on elbow flexor hypertrophy in the cable curl exercise. Front Physiol. 2026;17:1750722. doi:10.3389/fphys.2026.1750722", url: "https://europepmc.org/article/MED/41988507" },
    ],
  },
  {
    id: "curl-mind-muscle",
    grade: "A",
    text: "Focusing on squeezing the biceps grew the arm more (12.4% vs 6.9%) than focusing on just lifting the weight, but the same trick made no difference for the thighs.",
    sources: [
      { citation: "Schoenfeld BJ, Vigotsky A, Contreras B, et al. Differential effects of attentional focus strategies during long-term resistance training. Eur J Sport Sci. 2018;18(5):705-712. doi:10.1080/17461391.2018.1447020", url: "https://europepmc.org/article/MED/29533715" },
    ],
  },
  {
    id: "overhead-triceps-growth",
    grade: "A",
    text: "Overhead cable triceps extensions grew the whole triceps about 1.4 times more than pushdowns (about 20% vs 14%), even though lighter weights were used.",
    sources: [
      { citation: "Maeo S, Wu Y, Huang M, et al. Triceps brachii hypertrophy is substantially greater after elbow extension training performed in the overhead versus neutral arm position. Eur J Sport Sci. 2023;23(7):1240-1250. doi:10.1080/17461391.2022.2100279", url: "https://europepmc.org/article/MED/35819335" },
    ],
  },
  {
    id: "pushdown-lateral-head-myth",
    grade: "A",
    text: "Myth check: overhead extensions did not just grow the long head, because the lateral and medial heads that pushdowns supposedly target also grew more with overhead work.",
    sources: [
      { citation: "Maeo S, Wu Y, Huang M, et al. Eur J Sport Sci. 2023;23(7):1240-1250. doi:10.1080/17461391.2022.2100279", url: "https://europepmc.org/article/MED/35819335" },
    ],
  },
  {
    id: "skull-crusher-anatomy",
    grade: "C",
    text: "Lying triceps extensions put the upper arm partway overhead, which stretches the triceps long head more than a pushdown but less than a full overhead extension.",
    sources: [
      { citation: "Maeo S, Wu Y, Huang M, et al. Eur J Sport Sci. 2023;23(7):1240-1250 (mechanism only). doi:10.1080/17461391.2022.2100279", url: "https://europepmc.org/article/MED/35819335" },
    ],
  },
  {
    id: "lunge-emg",
    grade: "B",
    text: "In barbell-loaded single-leg squats, forward lunges and lateral step-ups, two of the front-thigh muscles (vastus lateralis and medialis) showed the most activity, followed by the side and main glutes, while the rectus femoris front-thigh muscle ranked below the glutes.",
    sources: [
      { citation: "Muyor JM, Martín-Fuentes I, Rodríguez-Ridao D, Antequera-Vique JA. Electromyographic activity in the gluteus medius, gluteus maximus, biceps femoris, vastus lateralis, vastus medialis and rectus femoris during the Monopodal Squat, Forward Lunge and Lateral Step-Up exercises. PLoS One. 2020;15(4):e0230841. doi:10.1371/journal.pone.0230841", url: "https://europepmc.org/article/MED/32236133" },
    ],
  },
];

// library exercise id → the notes that name it
const BY_EXERCISE: Record<string, [string, Attach][]> = {
  "ex-45-back-extension": [["hip-extension-bflh", "this"]],
  "ex-band-row": [["band-row-anatomy", "this"]],
  "ex-barbell-back-squat": [["squat-depth-glutes", "this"], ["squat-depth-quads", "this"], ["squat-no-hamstrings", "this"], ["squat-rectus-femoris", "this"], ["hipthrust-vs-squat-glutes", "this"], ["hipthrust-emg-numbers", "this"], ["glute-medius-little-growth", "this"]],
  "ex-barbell-bench-press": [["incline-bench-upper-chest", "this"], ["incline-angle-emg", "this"], ["flat-bench-emg", "this"], ["machine-chest-press-emg", "variation"], ["pushup-vs-bench-growth", "variation"]],
  "ex-barbell-curl": [["pulling-grows-biceps", "variation"], ["curl-mind-muscle", "variation"]],
  "ex-barbell-hip-thrust": [["hipthrust-vs-squat-glutes", "this"], ["hipthrust-emg-not-growth", "this"], ["hipthrust-emg-numbers", "this"], ["glute-medius-little-growth", "this"]],
  "ex-barbell-lunge": [["lunge-emg", "this"]],
  "ex-barbell-overhead-press": [["overhead-press-anatomy", "this"]],
  "ex-bodyweight-squat": [["bodyweight-squat-older-adults", "variation"]],
  "ex-cable-curl": [["behind-body-curl-myth", "this"]],
  "ex-cable-lateral-raise": [["lateral-raise-cable-vs-dumbbell", "this"]],
  "ex-cable-overhead-triceps-extension": [["overhead-triceps-growth", "this"], ["pushdown-lateral-head-myth", "this"]],
  "ex-chin-up": [["pullup-grip", "this"]],
  "ex-close-grip-lat-pulldown": [["pulldown-grip-width-myth", "this"]],
  "ex-conventional-deadlift": [["deadlift-anatomy", "this"]],
  "ex-dumbbell-bench-press": [["flat-bench-emg", "variation"]],
  "ex-dumbbell-calf-raise": [["standing-vs-seated-calf", "variation"], ["calf-stretched-half", "variation"], ["calf-toe-direction", "variation"]],
  "ex-dumbbell-curl": [["pulling-grows-biceps", "variation"], ["curl-mind-muscle", "variation"]],
  "ex-dumbbell-lateral-raise": [["lateral-raise-cable-vs-dumbbell", "this"]],
  "ex-dumbbell-lunge": [["lunge-emg", "variation"]],
  "ex-dumbbell-romanian-deadlift": [["rdl-anatomy", "this"]],
  "ex-dumbbell-shoulder-press": [["overhead-press-anatomy", "variation"]],
  "ex-glute-bridge": [["glute-bridge-anatomy", "this"]],
  "ex-incline-barbell-bench-press": [["incline-bench-upper-chest", "this"], ["incline-angle-emg", "this"]],
  "ex-incline-dumbbell-bench-press": [["incline-bench-upper-chest", "variation"], ["incline-angle-emg", "variation"]],
  "ex-incline-machine-chest-press": [["incline-bench-upper-chest", "variation"]],
  "ex-lat-pulldown": [["pulldown-grip-width-myth", "this"], ["pulldown-front", "this"], ["pulling-grows-biceps", "this"]],
  "ex-leg-extension": [["leg-press-glutes", "this"], ["leg-extension-rectus-femoris", "this"], ["leg-extension-stretched-half", "this"]],
  "ex-leg-press": [["squat-rectus-femoris", "this"], ["leg-press-glutes", "this"], ["leg-extension-rectus-femoris", "this"]],
  "ex-lying-leg-curl": [["seated-vs-lying-leg-curl", "this"]],
  "ex-machine-chest-press": [["machine-chest-press-emg", "this"]],
  "ex-machine-preacher-curl": [["curl-stretched-range", "variation"], ["preacher-curl-partials-trained", "variation"]],
  "ex-machine-shoulder-press": [["overhead-press-anatomy", "variation"]],
  "ex-neutral-grip-pull-up": [["pullup-grip", "this"]],
  "ex-nordic-hamstring-curl": [["hip-extension-bflh", "this"], ["nordic-curl", "this"]],
  "ex-one-arm-dumbbell-row": [["pulling-grows-biceps", "this"]],
  "ex-overhead-triceps-extension": [["overhead-triceps-growth", "variation"], ["pushdown-lateral-head-myth", "variation"]],
  "ex-plank": [["plank-long-lever", "this"], ["plank-anatomy", "this"]],
  "ex-preacher-curl": [["curl-stretched-range", "this"], ["preacher-curl-partials-trained", "this"]],
  "ex-pull-up": [["pullup-grip", "this"]],
  "ex-push-up": [["pushup-vs-bench-growth", "this"], ["band-pushup-strength", "variation"]],
  "ex-reverse-lunge": [["lunge-emg", "variation"]],
  "ex-romanian-deadlift": [["nordic-curl", "this"], ["rdl-anatomy", "this"]],
  "ex-rope-triceps-pushdown": [["overhead-triceps-growth", "variation"], ["pushdown-lateral-head-myth", "variation"]],
  "ex-seated-barbell-military-press": [["overhead-press-anatomy", "this"]],
  "ex-seated-cable-row": [["seated-row-elbows", "this"]],
  "ex-seated-calf-raise": [["standing-vs-seated-calf", "this"], ["seated-calf-soleus-myth", "this"]],
  "ex-seated-leg-curl": [["seated-vs-lying-leg-curl", "this"]],
  "ex-skullcrusher": [["skull-crusher-anatomy", "this"]],
  "ex-standing-calf-raise": [["standing-vs-seated-calf", "this"], ["seated-calf-soleus-myth", "this"], ["calf-stretched-half", "variation"], ["calf-toe-direction", "variation"]],
  "ex-step-up": [["lunge-emg", "variation"]],
  "ex-triceps-pushdown": [["overhead-triceps-growth", "this"], ["pushdown-lateral-head-myth", "this"]],
  "ex-walking-lunge": [["lunge-emg", "variation"]],
  "ex-wide-grip-lat-pulldown": [["pulldown-grip-width-myth", "this"]],
  "ex-wide-grip-pull-up": [["pullup-grip", "this"]],
  "ex-wide-grip-seated-cable-row": [["seated-row-elbows", "this"]],
};

// normalised name or alias → library exercise id, for exercises that have notes
const ID_BY_NAME: Record<string, string> = {
  "45° back extension": "ex-45-back-extension",
  "band row": "ex-band-row",
  "barbell back squat": "ex-barbell-back-squat",
  "barbell bench press": "ex-barbell-bench-press",
  "barbell curl": "ex-barbell-curl",
  "barbell hip thrust": "ex-barbell-hip-thrust",
  "barbell lunge": "ex-barbell-lunge",
  "barbell overhead press": "ex-barbell-overhead-press",
  "bodyweight squat": "ex-bodyweight-squat",
  "cable curl": "ex-cable-curl",
  "cable lateral raise": "ex-cable-lateral-raise",
  "cable overhead triceps extension": "ex-cable-overhead-triceps-extension",
  "chin up": "ex-chin-up",
  "close grip lat pulldown": "ex-close-grip-lat-pulldown",
  "conventional deadlift": "ex-conventional-deadlift",
  "dumbbell bench press": "ex-dumbbell-bench-press",
  "dumbbell calf raise": "ex-dumbbell-calf-raise",
  "dumbbell curl": "ex-dumbbell-curl",
  "dumbbell lateral raise": "ex-dumbbell-lateral-raise",
  "dumbbell lunge": "ex-dumbbell-lunge",
  "dumbbell romanian deadlift": "ex-dumbbell-romanian-deadlift",
  "dumbbell shoulder press": "ex-dumbbell-shoulder-press",
  "flat dumbbell press": "ex-dumbbell-bench-press",
  "glute bridge": "ex-glute-bridge",
  "incline barbell bench press": "ex-incline-barbell-bench-press",
  "incline dumbbell bench press": "ex-incline-dumbbell-bench-press",
  "incline dumbbell press": "ex-incline-dumbbell-bench-press",
  "incline machine chest press": "ex-incline-machine-chest-press",
  "lat pulldown": "ex-lat-pulldown",
  "leg extension": "ex-leg-extension",
  "leg press": "ex-leg-press",
  "lying leg curl": "ex-lying-leg-curl",
  "machine chest press": "ex-machine-chest-press",
  "machine preacher curl": "ex-machine-preacher-curl",
  "machine shoulder press": "ex-machine-shoulder-press",
  "neutral grip pull up": "ex-neutral-grip-pull-up",
  "nordic hamstring curl": "ex-nordic-hamstring-curl",
  "one arm dumbbell row": "ex-one-arm-dumbbell-row",
  "overhead triceps extension": "ex-overhead-triceps-extension",
  "plank": "ex-plank",
  "preacher curl": "ex-preacher-curl",
  "pull up": "ex-pull-up",
  "push up": "ex-push-up",
  "reverse lunge": "ex-reverse-lunge",
  "romanian deadlift": "ex-romanian-deadlift",
  "rope triceps pushdown": "ex-rope-triceps-pushdown",
  "seated barbell military press": "ex-seated-barbell-military-press",
  "seated cable row": "ex-seated-cable-row",
  "seated calf raise": "ex-seated-calf-raise",
  "seated leg curl": "ex-seated-leg-curl",
  "skullcrusher": "ex-skullcrusher",
  "standing calf raise": "ex-standing-calf-raise",
  "step up": "ex-step-up",
  "triceps pushdown": "ex-triceps-pushdown",
  "walking lunge": "ex-walking-lunge",
  "wide grip lat pulldown": "ex-wide-grip-lat-pulldown",
  "wide grip pull up": "ex-wide-grip-pull-up",
  "wide grip seated cable row": "ex-wide-grip-seated-cable-row",
};

const IN_CATEGORY: Record<string, (ex: Exercise) => boolean> = {
  "equipment:band": (ex) => ex.mode === "band" || ex.equipment === "band",
  "muscle:core": (ex) => ex.muscle === "core",
};

const BY_CATEGORY: [string, string][] = [
  ["bands-vs-weights-strength", "equipment:band"],
  ["band-colour-not-weight", "equipment:band"],
  ["ab-spot-reduction-myth", "muscle:core"],
];

const norm = (name: string): string => {
  const s = name.toLowerCase().trim()
    .replace(/[-_]+/g, " ").replace(/\s+/g, " ")
    .replace(/\bflye\b/g, "fly").replace(/\bskull crusher\b/g, "skullcrusher")
    .replace(/\btricep\b/g, "triceps");
  return s.replace(/(\S{2,}[^s])s$/, "$1");
};

const NOTE_BY_ID = new Map(STUDY_NOTES.map((n, i) => [n.id, { n, i }]));
const GRADE_RANK: Record<Grade, number> = { A: 0, B: 1, C: 2 };
const ATTACH_RANK: Record<Attach, number> = { this: 0, variation: 1, category: 2 };

/** Every study note for this exercise: A, then B, then C (then this → variation → category). */
export function notesFor(ex: Exercise): StudyNote[] {
  const found = new Map<string, Attach>();
  const keep = (id: string, attach: Attach) => {
    const prev = found.get(id);
    if (!prev || ATTACH_RANK[attach] < ATTACH_RANK[prev]) found.set(id, attach);
  };
  const key = [ex.mergedInto, ex.id].find((k) => k && BY_EXERCISE[k]) ?? ID_BY_NAME[norm(ex.name)];
  for (const [nid, attach] of (key && BY_EXERCISE[key]) || []) keep(nid, attach);
  for (const [nid, cat] of BY_CATEGORY) if (IN_CATEGORY[cat](ex)) keep(nid, "category");
  return [...found]
    .flatMap(([nid, attach]) => {
      const hit = NOTE_BY_ID.get(nid);
      return hit ? [{ ...hit, attach }] : [];
    })
    .sort((a, b) => GRADE_RANK[a.n.grade] - GRADE_RANK[b.n.grade] || ATTACH_RANK[a.attach] - ATTACH_RANK[b.attach] || a.i - b.i)
    .map(({ n, attach }) => ({ ...n, attach }));
}
