// What a reminder row MEANS. One copy, read by the read door, the write door and
// the 15-minute job.
//
// WHY THIS FILE EXISTS AT ALL
//
// Three different places now have an opinion about the same four columns:
//   · the read door lists what is pending,
//   · the write door cancels and edits,
//   · cron-reminders decides what to deliver and where a repeating one goes next.
//
// If "pending" means `sent_at is null` in one of them and `sent_at is null and
// canceled_at is null` in another, then a cancelled reminder is invisible in the
// list and still arrives on a lock screen — which is the exact shape of the bug
// this repo has already paid for twice. cron-notify carried its own copy of the
// bill cadence maths and told the phones a semiannual bill was due every month;
// the write door carried its own copy of the secret comparison and accepted a
// placeholder the read door refused. Both were a second opinion about one rule.
//
// So the rule lives here once, as functions, and the doors ask.
//
// WHY NOT src/lib. Rule 3 says that when a SCREEN assembles something, extract it
// into src/lib and import it on both sides. No screen assembles this: nothing in
// `src/` reads or writes the `reminders` table — there is no reminders screen in
// the app at all, which is precisely why the doors have to be the place a wrong
// reminder gets fixed. When the app grows that screen, this is the file it should
// import, moved to src/lib and regenerated by scripts/gen-muse-shared.mjs.
//
// NO ARITHMETIC ON MONEY, NO CLOCK. The only numbers here are minutes and list
// offsets, and every instant arrives as an argument.

import { azFields, azWallClock, instantOf } from "./az.ts";
import { MESSAGE_CAP, MUSE_MARKER, scrub, scrubCap, wasChanged } from "./scrub.ts";

/** How a reminder repeats. The database has the same three in a check constraint
 *  (schema_v36_muse_bridge.sql), and cron-reminders/schedule.ts steps them. */
export const REPEATS = ["once", "daily", "weekly"] as const;
export type Repeats = (typeof REPEATS)[number];

export function isRepeats(v: unknown): v is Repeats {
  return typeof v === "string" && (REPEATS as readonly string[]).includes(v);
}

/**
 * The longest a stored message can be, which is the database's own check:
 * `char_length(message) between 1 and 120`.
 *
 * It is bigger than MESSAGE_CAP (80) because the stored line is the marker plus
 * the cap, and because a row the app writes one day is not bound by the door's
 * input rule. A tool reading a row out loud has to allow for the column, not for
 * the rule the door applies on the way in — scrub() REFUSES rather than slices, so
 * a cap that is too small here turns a perfectly good reminder into "a reminder".
 */
export const STORED_MESSAGE_MAX = 120;

/** The raw message length the door will even look at before cleaning. */
export const MESSAGE_INPUT_MAX = 200;

/**
 * cron-reminders runs on a 15-minute schedule, so this is the honest grain to
 * promise. Saying "at 11:00 exactly" would be a promise the pipeline does not
 * make.
 */
export const DELIVERY_GRAIN_MIN = 15;

/** How far ahead a reminder may be set, or moved. */
export const REMIND_MAX_DAYS = 365;

/** One reminder, as every door reads it. snake_case stays at the database edge. */
export interface ReminderRow {
  id: string;
  person: string;
  /** Already carries its marker and was capped and cleaned when it was written. */
  message: string;
  dueAt: string;
  repeats: string;
  source: string;
  /** Set once a 'once' reminder has been delivered. A repeating one never gets
   *  one — it moves its own dueAt forward instead, which is why "has it fired" and
   *  "is it finished" are different questions. */
  sentAt: string | null;
  /**
   * For a REPEATING reminder, the last time it actually fired.
   *
   * A repeating row never gets a `sentAt` — it moves its own dueAt forward instead — so
   * without this there is no way to answer "has the daily one been going out?" at all.
   * The column has been in schema_v36 since the start; nothing read it until phase 2's
   * schedule.reminders did, and the health branch had added a private ReminderRow here
   * to carry it. It belongs on the shared one: this interface is what the read door, the
   * write door and cron-reminders all agree a reminder is, and a second spelling of that
   * is the drift scripts/check-categorizer-sync.mjs keeps this file in SHARED_ONLY for.
   */
  lastSentAt: string | null;
  /** Set when somebody called schedule.cancel_reminder. Not a delete: no door has
   *  a delete verb, and a cancelled row is the record that it was cancelled. */
  canceledAt: string | null;
}

/** Why this reminder will never arrive, or null when it still will. */
export type Closed = "delivered" | "cancelled";

/**
 * Is this reminder finished with, and how?
 *
 * The ONE definition. `sent_at` closes a 'once' reminder; `canceled_at` closes any
 * of them. A repeating reminder with a `last_sent_at` and no `canceled_at` is very
 * much still pending, however many times it has already fired.
 */
export function closedBecause(r: ReminderRow): Closed | null {
  if (r.canceledAt) return "cancelled";
  if (r.sentAt) return "delivered";
  return null;
}

export function isPending(r: ReminderRow): boolean {
  return closedBecause(r) === null;
}

/**
 * This person's pending reminders, soonest first.
 *
 * Ordered by the due time and then by id, so the order is total — two reminders
 * set for the same minute must not swap places between two calls, or a page
 * boundary shows one of them twice and the other never.
 */
export function pendingFor(rows: readonly ReminderRow[], person: string): ReminderRow[] {
  return rows
    .filter((r) => r.person === person && isPending(r))
    .sort((a, b) => (a.dueAt === b.dueAt ? a.id.localeCompare(b.id) : a.dueAt.localeCompare(b.dueAt)));
}

/**
 * One reminder, as it goes out of a door: scrubbed, and with its time in words.
 *
 * A `type` and not an `interface`, deliberately: only a type alias of an object
 * literal gets TypeScript's implicit index signature, which is what lets a tool
 * drop one of these straight into a reply typed `{ [k: string]: Json }` instead of
 * copying every field across by hand — and a hand copy is where a field gets
 * quietly dropped.
 */
export type ReminderOut = {
  id: string;
  message: string;
  due_at: string;
  /** The same moment as Arizona wall-clock words, or null when the stored
   *  timestamp could not be read. Never a guess. */
  due_arizona: string | null;
  repeats: string;
  source: string;
  /** Its time has passed and it has not been delivered — the 15-minute job is
   *  behind, or was down. Null when the stored time could not be read, because
   *  "not overdue" would be a claim and this is an absence of one. */
  overdue: boolean | null;
};

/**
 * A row, made safe to say.
 *
 * `nowAz` is the request's Arizona "now" — the field-carrying Date nowAZ() builds,
 * NOT an instant. The due time is put through azFields() so both sides of the
 * comparison are the same kind of thing. Comparing an Arizona-fielded Date against
 * a real instant is wrong by the runtime's own offset, which on these doors is
 * seven hours, which is most of a night shift.
 */
export function describe(r: ReminderRow, nowAz: Date): ReminderOut {
  const due = instantOf(r.dueAt);
  return {
    id: r.id,
    // Rule 4: scrubbed on the way out even though it was scrubbed on the way in.
    // A row the app writes one day will not have been.
    message: scrub(r.message, STORED_MESSAGE_MAX) ?? "a reminder I cannot repeat safely",
    due_at: r.dueAt,
    due_arizona: due ? azWallClock(due) : null,
    repeats: isRepeats(r.repeats) ? r.repeats : "once",
    source: scrub(r.source, 24) ?? "unknown",
    overdue: due ? azFields(due).getTime() <= nowAz.getTime() : null,
  };
}

// ── the message rule, in one place ───────────────────────────────────────────

export type MessageResult =
  | { ok: true; message: string; trimmed: boolean }
  | { ok: false; say: string };

/**
 * The message a reminder is stored with: cleaned, capped, and carrying the marker.
 *
 * ONE COPY, because `schedule.remind` and `schedule.update_reminder` both set a
 * message and a second spelling is how one of them ends up storing a line the
 * other would have refused. The marker in particular has to go on in both: it is
 * the only thing on a lock screen that says an assistant wrote this and Homebase
 * did not.
 *
 * It returns the refusal SENTENCE rather than a code, because that sentence is
 * said to a person as it stands.
 */
export function messageFor(raw: unknown): MessageResult {
  const said = typeof raw === "string" ? raw.trim() : "";
  if (!said) return { ok: false, say: "Tell me what the reminder should say." };
  const tooLong = (n: number) =>
    `That reminder is ${n} characters. Keep it under ${MESSAGE_CAP} — it has to fit on a lock screen.`;
  if (said.length > MESSAGE_INPUT_MAX) return { ok: false, say: tooLong(said.length) };
  const clean = scrubCap(said, MESSAGE_INPUT_MAX);
  if (!clean) {
    return { ok: false, say: "There was nothing left of that reminder once the links were taken out." };
  }
  if (clean.length > MESSAGE_CAP) return { ok: false, say: tooLong(clean.length) };
  return { ok: true, message: MUSE_MARKER + clean, trimmed: wasChanged(said, clean) };
}

/** The one sentence said when cleaning took something out. Said only when true. */
export const TRIMMED_SAYS = " I shortened it and took out anything link-shaped.";

// ── what a person is told about a reminder that is already over ──────────────

/**
 * The refusal for a reminder that cannot be touched any more, as one sentence.
 *
 * `verb` is what the caller was trying to do ("cancel", "change"), because
 * "nothing left to cancel" and "nothing left to change" are the two ways this
 * happens and a person should hear which.
 *
 * WHY THIS IS A REFUSAL AND NOT A SHRUG. A cancel that answered "done" for a
 * reminder that already went out is the worst outcome in this whole tool: the
 * person hears it was stopped, the push is already on their phone, and the two
 * facts never meet. So it fails, out loud, with the time it went out.
 */
export function overSays(closed: Closed, verb: string, whenAz: string | null): string {
  const when = whenAz ? ` at ${whenAz}` : "";
  return closed === "delivered"
    ? `That reminder already went out${when}. There is nothing left to ${verb}.`
    : `That reminder was already cancelled${when}. There is nothing left to ${verb}.`;
}

// ── what cannot be asked for, said once ──────────────────────────────────────
//
// Read out by API.md and by the write door's own description, so an assistant that
// is asked for "every Tuesday and Thursday" says the true thing instead of storing
// something that sounds close.
export const REPEAT_LIMITS = [
  "Only once, daily and weekly exist. There is no monthly, no yearly, no every-other-day, no twice a day, and no hourly.",
  "A weekly reminder repeats on the weekday of the time it was set for. Two different weekdays is two reminders.",
  "There is no end date and no count. A daily reminder runs until somebody cancels it, and it takes up one of the waiting slots the whole time.",
  "A repeating reminder more than 12 hours late is skipped for that slot and moves on to the next one, so an outage does not empty a night onto a lock screen at once.",
] as const;
