// AUTO-GENERATED from Gino's hand-categorized MasterLedger (485 txns, 131 merchants).
// Each key is a normalized merchant (see merchantKey in categorize.ts); the value is
// Gino's own category label. Regenerate with Desktop/Finances/_gendict.cjs.
// HisCategory is the raw label; categorize.ts maps it to an app category + a kind.

export const MERCHANT_CATEGORY: Record<string, string> = {
  "365 MARKET J": "Gas/Auto/Convenience",
  "99 RANCH": "Groceries",
  "AFFIRM": "Debt: Affirm",
  "AFFIRM.COM PAYME": "Debt: Affirm",
  "AFFIRM.COM PAYMENTS": "Debt: Affirm",
  "AMAZON MKTPL": "Shopping",
  "AMAZON PRIME": "Subscriptions/Digital",
  "AMAZON PRIME PMTS": "Subscriptions/Digital",
  "AMERICAN AIR00123359588": "Travel/Other",
  "AMERICAN AIR00144938190": "Travel/Other",
  "ANTHROPIC": "Subscriptions/Digital",
  "APPLE COM BILL": "Subscriptions/Digital",
  "APPLE.COM/BILL": "Subscriptions/Digital",
  "ARIZONA STATE UN": "Income: Paycheck",
  "ASU US PASSPORT OFFICE": "Travel/Other",
  "AUDIBLE": "Subscriptions/Digital",
  "AZ DEPT OF REV": "Income: Tax refund",
  "BANKAMERIDEALS CASHBACK": "Cashback",
  "BASS PRO STORE": "Shopping",
  "BKOFAMERICA ATM": "Cash deposit",
  "BOBS TIRES": "Gas/Auto/Convenience",
  "CAFE ZUPAS - ASU TEMPE": "Dining/Takeout",
  "CAMPUS BOOKSTO": "Shopping",
  "CHEVRON": "Gas/Auto/Convenience",
  "CHIPOTLE MEX G": "Dining/Takeout",
  "CHUBBY SKEWERS PHOENI": "Dining/Takeout",
  "CIRCLE K": "Gas/Auto/Convenience",
  "CIRCLE K #": "Gas/Auto/Convenience",
  "CLAUDE.AI SUBSCRIPTION": "Subscriptions/Digital",
  "COCINA MADRIGAL": "Dining/Takeout",
  "CTLP": "Other",
  "CVS/PHARMACY #": "Health/Personal",
  "DAISO - MESA MAIN MARK": "Groceries",
  "DD": "Dining/Takeout",
  "DUPLEX TEA": "Dining/Takeout",
  "DUTCH BROS AZ1501 PAYSO": "Dining/Takeout",
  "E.T. TEA": "Dining/Takeout",
  "FANTUAN DELIVERY": "Groceries",
  "FEDEX OFFICE": "Travel/Other",
  "FRONTIER AI TKT36K": "Subscriptions/Digital",
  "FRYS FUEL": "Gas/Auto/Convenience",
  "GEMBA AUTOMOTIVE TEMPE": "Gas/Auto/Convenience",
  "GOOGLE": "Subscriptions/Digital",
  "H MART MESA LLC": "Groceries",
  "HAIDILAO HOT POT ARIZON": "Dining/Takeout",
  "HAIRFLIX": "Health/Personal",
  "HECHALOU": "Dining/Takeout",
  "IKEA TEMPE": "Shopping",
  "IKEA TEMPE RES": "Shopping",
  "INTUIT": "Other",
  "IRS": "Other",
  "IRS TREAS": "Income: Tax refund",
  "ITCH.IO - GAME STORE": "Subscriptions/Digital",
  "JACK IN THE BOX": "Dining/Takeout",
  "JLCPCB": "Subscriptions/Digital",
  "KINDLE SVCS": "Subscriptions/Digital",
  "KWIKCORNER": "Gas/Auto/Convenience",
  "LAMBDA CLOUD": "Subscriptions/Digital",
  "MEET FRESH - MESA": "Dining/Takeout",
  "MEKONG SUPERMA": "Groceries",
  "MEKONG SUPERMARKET": "Groceries",
  "MICRO MART": "Gas/Auto/Convenience",
  "MOBILE BANKING PAYMENT TO CR": "Debt: Credit card",
  "NIKEPOS_US": "Shopping",
  "NOLLIE MA": "Rent",
  "NORDSTROM DIRECT": "Shopping",
  "NORDSTROM RACK": "Shopping",
  "ONLINE BANKING TRANSFER FROM": "Internal: account transfer",
  "ONLINE BANKING TRANSFER TO C": "Internal: account transfer",
  "PANDA EXPRESS TBIT LAX": "Dining/Takeout",
  "PANDAREMIT US": "Remittance (abroad)",
  "PASSPORTVISAEXPRESS.COM": "Travel/Other",
  "PAUL'S ACE HAR": "Gas/Auto/Convenience",
  "PETSMART #": "Pets",
  "QT": "Gas/Auto/Convenience",
  "RAISING CANES": "Dining/Takeout",
  "REPLIT, INC.": "Subscriptions/Digital",
  "RMTLY": "Remittance (abroad)",
  "ROSS STORE": "Shopping",
  "ROSS STORES": "Shopping",
  "SAFEWAY": "Groceries",
  "SHELL SERVICE": "Gas/Auto/Convenience",
  "SNACK": "Dining/Takeout",
  "SPOT PET": "Pets",
  "SPOTIFY P4251562AE": "Subscriptions/Digital",
  "SPOTIFY P4364C3431": "Subscriptions/Digital",
  "SPOTIFY USA": "Subscriptions/Digital",
  "SQ": "Other",
  "SRP": "Utilities: Electric",
  "STARBUCKS": "Dining/Takeout",
  "SUN DEVIL MARKETPL": "Groceries",
  "SWA": "Travel/Other",
  "SZECHWAN NOODLE": "Dining/Takeout",
  "T-SWIRL CREPE ARIZONA": "Dining/Takeout",
  "TARGET T-1429": "Shopping",
  "TARGET T-2176": "Shopping",
  "TC @ TSMC ARIZONA": "Other",
  "THE HOME DEPOT": "Shopping",
  "TMOBILE": "Utilities: Phone",
  "TMOBILE PREPAI": "Utilities: Phone",
  "TRADER JOE S #": "Groceries",
  "TREASURE OF TECH": "Income: Paycheck",
  "TST": "Dining/Takeout",
  "TVM SMITHMARTINAPACH": "Other",
  "UBER": "Rideshare/Delivery",
  "UEP": "Other",
  "ULTA": "Shopping",
  "VANS GLENDALE": "Shopping",
  "VZ WIRELESS VW": "Utilities: Phone",
  "WAL-MART": "Groceries",
  "WALGREENS STOR": "Health/Personal",
  "WALMART.COM": "Groceries",
  "WHOLEFDS TMP#1": "Groceries",
  "WM SUPERCENTER": "Groceries",
  "XAI LLC": "Subscriptions/Digital",
  "YAMI.COM": "Groceries",
  "ZELLE PAYMENT FROM ANGEL BER": "Zelle: friends/family",
  "ZELLE PAYMENT FROM GIOVANNI ": "Internal: spouse",
  "ZELLE PAYMENT FROM XINYAN LI": "Internal: spouse",
  "ZELLE PAYMENT FROM YONGXIN C": "Zelle: friends/family",
  "ZELLE PAYMENT TO ANGEL BRO B": "Zelle: friends/family",
  "ZELLE PAYMENT TO BABE": "Internal: spouse",
  "ZELLE PAYMENT TO GIO": "Internal: spouse",
  "ZELLE PAYMENT TO GIO FOR GRO": "Internal: spouse",
  "ZELLE PAYMENT TO GIO FOR REN": "Internal: spouse",
  "ZELLE PAYMENT TO MENGDI": "Zelle: friends/family",
  "ZELLE PAYMENT TO MON": "Family support",
  "ZELLE PAYMENT TO MON FOR SOM": "Family support",
  "ZELLE PAYMENT TO QI LIN": "Zelle: friends/family",
  "ZELLE PAYMENT TO YUNJING LAI": "Zelle: friends/family",
  "ZHENG XIN": "Dining/Takeout",
};
