// Inject the `unit: {name, grams}` field into src/lib/foodData.ts using the
// classifications the food-unit-classify workflow wrote to units/*.json.
//   node scripts/fooddata/apply-units.mjs

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const OUT = join(here, "..", "..", "src", "lib", "foodData.ts");
const UNITS = join(here, "units");

// ── load the current foods (eval the object-literal array) ──
const txt = readFileSync(OUT, "utf8");
const m = txt.match(/BUNDLED_FOODS:\s*Food\[\]\s*=\s*(\[[\s\S]*\]);/);
const foods = eval(m[1]);

// ── build id → unit map from the workflow output ──
const byId = new Map();
let bad = 0;
for (const f of readdirSync(UNITS).filter((x) => x.endsWith(".json"))) {
  let arr;
  try {
    arr = JSON.parse(readFileSync(join(UNITS, f), "utf8"));
  } catch (e) {
    console.error(`✗ ${f}: ${e.message}`);
    continue;
  }
  for (const u of Array.isArray(arr) ? arr : []) {
    const name = typeof u.unit === "string" ? u.unit.trim().toLowerCase() : "";
    const grams = typeof u.grams === "string" ? parseFloat(u.grams) : u.grams;
    if (!u.id || !name || !Number.isFinite(grams) || grams <= 0 || grams > 2000) {
      bad++;
      continue;
    }
    byId.set(u.id, { name, grams: Math.round(grams * 10) / 10 });
  }
}

let applied = 0;
for (const f of foods) {
  const u = byId.get(f.id);
  if (u) {
    f.unit = u;
    applied++;
  } else {
    delete f.unit;
  }
}

// ── re-emit (same shape as merge.mjs + the unit field) ──
const body = foods
  .map((f) => {
    const parts = [
      `id: ${JSON.stringify(f.id)}`,
      `name: ${JSON.stringify(f.name)}`,
      `role: ${JSON.stringify(f.role)}`,
      `kcal: ${f.kcal}`,
      `p: ${f.p}`,
      `c: ${f.c}`,
      `f: ${f.f}`,
    ];
    if (f.serving != null) parts.push(`serving: ${f.serving}`);
    if (f.unit) parts.push(`unit: { name: ${JSON.stringify(f.unit.name)}, grams: ${f.unit.grams} }`);
    if (f.note != null) parts.push(`note: ${JSON.stringify(f.note)}`);
    return `  { ${parts.join(", ")} },`;
  })
  .join("\n");

const out = `import type { Food } from "./nutrition";

// ── The hidden offline food library ──────────────────────────────────────────
// A generated per-100g macro table (USDA-standard reference values) covering the
// common foods a household actually searches. NEVER shown as a list; surfaced
// only through search / barcode. Lazy-imported so it stays out of finance mode.
// GENERATED by scripts/fooddata/merge.mjs + apply-units.mjs — do not hand-edit.
// ${foods.length} foods, ${applied} with a natural unit.

export const BUNDLED_FOODS: Food[] = [
${body}
];
`;

writeFileSync(OUT, out, "utf8");
console.log(`applied units to ${applied}/${foods.length} foods · skipped ${bad} bad rows`);
console.log(`→ wrote ${OUT}`);
