// Merge the per-muscle exercise JSON (from the workout-exercise-library
// workflow) into src/lib/exerciseData.ts. Validates, dedupes by name, slug ids.
//   node scripts/exercisedata/merge.mjs

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const RAW = join(here, "raw");
const OUT = join(here, "..", "..", "src", "lib", "exerciseData.ts");

const MUSCLES = new Set(["chest", "back", "legs", "shoulders", "arms", "core", "fullbody", "cardio"]);
const EQUIP = new Set(["barbell", "dumbbell", "machine", "cable", "bodyweight", "kettlebell", "band", "other"]);
const TYPES = new Set(["compound", "isolation", "cardio"]);

const files = readdirSync(RAW).filter((f) => f.endsWith(".json"));
let raw = [];
const fileStats = [];
for (const f of files) {
  let arr;
  try {
    arr = JSON.parse(readFileSync(join(RAW, f), "utf8"));
  } catch (e) {
    console.error(`✗ ${f}: ${e.message}`);
    fileStats.push([f, "PARSE FAIL"]);
    continue;
  }
  if (!Array.isArray(arr)) { fileStats.push([f, "NOT ARRAY"]); continue; }
  for (const o of arr) raw.push({ ...o, _file: f.replace(/\.json$/, "") });
  fileStats.push([f, `${arr.length} rows`]);
}

const slug = (name) =>
  "ex-" + name.toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");

const rejects = [];
const clean = [];
const seenName = new Set();
const seenId = new Set();

for (const o of raw) {
  const name = typeof o.name === "string" ? o.name.trim() : "";
  if (!name) { rejects.push([o._file, "<no name>"]); continue; }
  const key = name.toLowerCase().replace(/\s+/g, " ");
  if (seenName.has(key)) continue;
  seenName.add(key);

  const muscle = MUSCLES.has(o.muscle) ? o.muscle : (MUSCLES.has(o._file) ? o._file : "other");
  const equipment = EQUIP.has(o.equipment) ? o.equipment : "other";
  const type = TYPES.has(o.type) ? o.type : (muscle === "cardio" ? "cardio" : "compound");

  let id = slug(name);
  if (!id || id === "ex-") id = "ex-x";
  let uid = id, i = 2;
  while (seenId.has(uid)) uid = `${id}-${i++}`;
  seenId.add(uid);

  clean.push({ id: uid, name, muscle, equipment, type });
}

clean.sort((a, b) => (a.muscle === b.muscle ? a.name.localeCompare(b.name) : a.muscle.localeCompare(b.muscle)));

const body = clean
  .map((e) => `  { id: ${JSON.stringify(e.id)}, name: ${JSON.stringify(e.name)}, muscle: ${JSON.stringify(e.muscle)}, equipment: ${JSON.stringify(e.equipment)}, type: ${JSON.stringify(e.type)} },`)
  .join("\n");

const out = `// ── The offline exercise library ─────────────────────────────────────────────
// Common gym exercises (name / muscle / equipment / type) the workout tracker
// searches when building routines or logging a session. Lazy-imported so it
// stays out of the finance-mode bundle. GENERATED by scripts/exercisedata/
// merge.mjs — do not hand-edit. ${clean.length} exercises.

export type Muscle = "chest" | "back" | "legs" | "shoulders" | "arms" | "core" | "fullbody" | "cardio";

export interface Exercise {
  id: string;
  name: string;
  muscle: Muscle;
  equipment: string;
  type: "compound" | "isolation" | "cardio";
}

export const BUNDLED_EXERCISES: Exercise[] = [
${body}
];
`;

writeFileSync(OUT, out, "utf8");

console.log("── files ──");
for (const [f, s] of fileStats) console.log(`  ${f.padEnd(18)} ${s}`);
console.log(`\nkept ${clean.length} exercises · rejected ${rejects.length}`);
if (rejects.length) for (const [f, n] of rejects.slice(0, 20)) console.log(`  [${f}] ${n}`);
console.log(`\n→ wrote ${OUT}`);
